
package com.mycompany.haar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RegistroVenta extends javax.swing.JFrame {
    private final Cconexion conexion;
    private DefaultTableModel modeloTabla; // Se agregó la declaración del modelo de la tabla
    
    public RegistroVenta() {
        initComponents();
        setLocation(25, 0);
        setTitle("Registro De Ventas");
        conexion = new Cconexion();
        modeloTabla = (DefaultTableModel) jTableVentas.getModel();
        cargarTabla();

        // Agregar ActionListener al botón jButtonEnviar
        jButtonEnviar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CalendarBoxFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jButtonEnviar = new javax.swing.JButton();
        jComboBoxVentas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(CalendarBoxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 70, 39));

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, "", null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "FechaCobro", "TipoCorte", "Servicio Extra", "MontoAdicional", "SubTotal", "IVA", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVentas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 870, 190));

        jButtonEnviar.setText("Solicitar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jComboBoxVentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario", "Diario Total", "Mensual", "Mensual Total", "Cortes", "Clientes" }));
        jComboBoxVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVentasActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1190, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
    String seleccion = (String) jComboBoxVentas.getSelectedItem();

        // Ejecutar la consulta SQL correspondiente según la selección del JComboBox
        if (seleccion.equals("Diario")) {
            ejecutarConsultaDiario();
        } else if (seleccion.equals("Diario Total")) {
            ejecutarConsultaDiarioTotal();
        } else if (seleccion.equals("Mensual")) {
            ejecutarConsultaMensual();
        } else if (seleccion.equals("Mensual Total")) {
            ejecutarConsultaMensualTotal();
        } else if (seleccion.equals("Cortes")) {
            ejecutarConsultaCortes();
        } else if (seleccion.equals("Clientes")) {
            ejecutarConsultaClientes();
        }
    }
     private void ejecutarConsultaDiario() {
     // Consulta SQL para Diario
        String query = "SELECT "
        + "CONCAT('Fecha: ', CONVERT(varchar, FechaCobro, 23)) AS Fecha, "
        + "Id, "
        + "Cliente, "
        + "TipoCorte, "
        + "ServicioExtra, "
        + "'Monto Adicional: $' + FORMAT(MontoAdicional, 'N2') AS MontoAdicional, "
        + "'Subtotal: $' + FORMAT(Subtotal, 'N2') AS Subtotal, "
        + "'IVA: $' + FORMAT(IVA, 'N2') AS IVA, "
        + "'Total: $' + FORMAT(Total, 'N2') AS Total "
        + "FROM Cobros "
        + "WHERE YEAR(FechaCobro) = YEAR(GETDATE()) AND MONTH(FechaCobro) = MONTH(GETDATE()) "
        + "ORDER BY FechaCobro";
        ejecutarConsulta(query);
    }//GEN-LAST:event_jButtonEnviarActionPerformed
    private void ejecutarConsultaDiarioTotal() {
     // Consulta SQL para Diario Total
        String query = "SELECT "
                + "CONCAT('Fecha: ', CONVERT(varchar, FechaCobro, 23)) AS Fecha, "
                + "Id, "
                + "Cliente, "
                + "TipoCorte, "
                + "ServicioExtra, "
                + "'Monto Adicional: $' + FORMAT(MontoAdicional, 'N2') AS MontoAdicional, "
                + "'Subtotal: $' + FORMAT(Subtotal, 'N2') AS Subtotal, "
                + "'IVA: $' + FORMAT(IVA, 'N2') AS IVA, "
                + "'Total: $' + FORMAT(Total, 'N2') AS Total "
                + "FROM Cobros "
                + "WHERE YEAR(FechaCobro) = YEAR(GETDATE()) AND MONTH(FechaCobro) = MONTH(GETDATE()) "
                + "ORDER BY FechaCobro";

        ejecutarConsulta(query);
    }

    private void ejecutarConsultaMensual() {
        // Consulta SQL para Mensual
        // Implementa esta consulta de manera similar a las anteriores
    }

    private void ejecutarConsultaMensualTotal() {
        // Consulta SQL para Mensual Total
        // Implementa esta consulta de manera similar a las anteriores
    }

    private void ejecutarConsultaCortes() {
        // Consulta SQL para Cortes
        // Implementa esta consulta de manera similar a las anteriores
    }

    private void ejecutarConsultaClientes() {
        // Consulta SQL para Clientes
        // Implementa esta consulta de manera similar a las anteriores
    }

    private void ejecutarConsulta(String query) {
       modeloTabla.setRowCount(0);
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            con = conexion.establecerConexion();
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                // Agregar los resultados de la consulta a la tabla
                Object[] fila = {
                    rs.getInt("Id"),
                    rs.getString("Cliente"),
                    rs.getString("FechaCobro"),
                    rs.getString("TipoCorte"),
                    rs.getString("ServicioExtra"),
                    rs.getString("MontoAdicional"),
                    rs.getString("Subtotal"),
                    rs.getString("IVA"),
                    rs.getString("Total")
                };
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private void jComboBoxVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVentasActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVenta().setVisible(true);
            }
        });
    }
     private void cargarTabla() {
        modeloTabla.setRowCount(0);
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            con = conexion.establecerConexion();
            String query = "SELECT * FROM Cobros";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("Id"),
                    rs.getString("Cliente"),
                    rs.getString("FechaCobro"),
                    rs.getString("TipoCorte"),
                    rs.getString("ServicioExtra"),
                    rs.getString("MontoAdicional"),
                    rs.getString("Subtotal"),
                    rs.getString("IVA"),
                    rs.getString("Total")
                };
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalendarBoxFecha;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JComboBox<String> jComboBoxVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVentas;
    // End of variables declaration//GEN-END:variables
}